<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>WeProtectExe.DotNet</AssemblyName>
    <RootNamespace>WeProtectExe.DotNetProtector</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- IL read/write library — https://github.com/0xd4d/dnlib -->
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>

</Project>
